/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package Interface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import static Interface.LoginWorkArea.backgroundBlue;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Akshay Gavandi
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

//        populateTree();
    }

//    public void populateTree() {
//        
//        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();
//
//        
//        
//        ArrayList<Network> networkList = system.getNetworkList();
//        ArrayList<Enterprise> enterpriseList;
//        ArrayList<Organization> organizationList;
//        Network network;
//        Enterprise enterprise;
//        Organization organization;
//
//        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
//        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
//        root.removeAllChildren();
//        root.insert(networks, 0);
//
//        DefaultMutableTreeNode networkNode;
//        DefaultMutableTreeNode enterpriseNode;
//        DefaultMutableTreeNode organizationNode;
//        for (int i = 0; i < networkList.size(); i++) {
//            network = networkList.get(i);
//            networkNode = new DefaultMutableTreeNode(network.getName());
//            networks.insert(networkNode, i);
//
//            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
//
//            for (int j = 0; j < enterpriseList.size(); j++) {
//                enterprise = enterpriseList.get(j);
//                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
//                networkNode.insert(enterpriseNode, j);
//
//                organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
//                for (int k = 0; k < organizationList.size(); k++) {
//                    organization = organizationList.get(k);
//                    organizationNode = new DefaultMutableTreeNode(organization.getName());
//                    enterpriseNode.insert(organizationNode, k);
//                }
//            }
//        }
//
//        model.reload();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemAdminWorkSplitPane = new javax.swing.JSplitPane();
        systemAdminWorkPane = new javax.swing.JPanel();
        systemAdminSplitPane = new javax.swing.JSplitPane();
        systemAdminProcessContainer = new javax.swing.JPanel();
        systemAdminMenu = new javax.swing.JPanel();
        manageNetworkJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        manageAdminJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        systemAdminWorkSplitPane.setDividerLocation(2000);

        systemAdminSplitPane.setDividerLocation(350);

        systemAdminProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        systemAdminProcessContainer.setLayout(new java.awt.CardLayout());
        systemAdminSplitPane.setRightComponent(systemAdminProcessContainer);

        systemAdminMenu.setBackground(new java.awt.Color(0, 51, 102));
        systemAdminMenu.setForeground(new java.awt.Color(255, 255, 255));

        manageNetworkJButton.setBackground(new java.awt.Color(0, 51, 102));
        manageNetworkJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageNetworkJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton.setText("Manage Network");
        manageNetworkJButton.setContentAreaFilled(false);
        manageNetworkJButton.setOpaque(true);
        manageNetworkJButton.setPreferredSize(new java.awt.Dimension(0, 50));
        manageNetworkJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageNetworkJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageNetworkJButtonMouseExited(evt);
            }
        });
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseJButton.setBackground(new java.awt.Color(0, 51, 102));
        manageEnterpriseJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageEnterpriseJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.setContentAreaFilled(false);
        manageEnterpriseJButton.setOpaque(true);
        manageEnterpriseJButton.setPreferredSize(new java.awt.Dimension(0, 50));
        manageEnterpriseJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageEnterpriseJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageEnterpriseJButtonMouseExited(evt);
            }
        });
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });

        manageAdminJButton.setBackground(new java.awt.Color(0, 51, 102));
        manageAdminJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageAdminJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageAdminJButton.setText("Manage Enterprise Admin");
        manageAdminJButton.setContentAreaFilled(false);
        manageAdminJButton.setOpaque(true);
        manageAdminJButton.setPreferredSize(new java.awt.Dimension(0, 50));
        manageAdminJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageAdminJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageAdminJButtonMouseExited(evt);
            }
        });
        manageAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminJButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(0, 1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("System Admin Work Area");

        javax.swing.GroupLayout systemAdminMenuLayout = new javax.swing.GroupLayout(systemAdminMenu);
        systemAdminMenu.setLayout(systemAdminMenuLayout);
        systemAdminMenuLayout.setHorizontalGroup(
            systemAdminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageNetworkJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(manageAdminJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(systemAdminMenuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        systemAdminMenuLayout.setVerticalGroup(
            systemAdminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemAdminMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(manageNetworkJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(manageAdminJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(834, Short.MAX_VALUE))
        );

        systemAdminSplitPane.setLeftComponent(systemAdminMenu);

        javax.swing.GroupLayout systemAdminWorkPaneLayout = new javax.swing.GroupLayout(systemAdminWorkPane);
        systemAdminWorkPane.setLayout(systemAdminWorkPaneLayout);
        systemAdminWorkPaneLayout.setHorizontalGroup(
            systemAdminWorkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(systemAdminSplitPane)
        );
        systemAdminWorkPaneLayout.setVerticalGroup(
            systemAdminWorkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(systemAdminSplitPane)
        );

        systemAdminWorkSplitPane.setLeftComponent(systemAdminWorkPane);

        add(systemAdminWorkSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminJButtonActionPerformed
//        // TODO add your handling code here:
//        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, system);
//        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);
//
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdminJButtonActionPerformed

    private void manageAdminJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdminJButtonMouseExited
        // TODO add your handling code here:
        manageAdminJButton.setBackground(backgroundBlue);
        manageAdminJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageAdminJButtonMouseExited

    private void manageAdminJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdminJButtonMouseEntered
        // TODO add your handling code here:
        manageAdminJButton.setBackground(Color.orange);
        manageAdminJButton.setForeground(Color.BLACK);

        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(systemAdminProcessContainer, system);
        systemAdminProcessContainer.add("ManageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout = (CardLayout)systemAdminProcessContainer.getLayout();
        layout.next(systemAdminProcessContainer);
    }//GEN-LAST:event_manageAdminJButtonMouseEntered

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed
//
//        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, system);
//        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);
//
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void manageEnterpriseJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonMouseExited
        // TODO add your handling code here:
        manageEnterpriseJButton.setBackground(backgroundBlue);
        manageEnterpriseJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageEnterpriseJButtonMouseExited

    private void manageEnterpriseJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonMouseEntered
        // TODO add your handling code here:
        manageEnterpriseJButton.setBackground(Color.orange);
        manageEnterpriseJButton.setForeground(Color.BLACK);

        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(systemAdminProcessContainer, system);
        systemAdminProcessContainer.add("ManageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout = (CardLayout)systemAdminProcessContainer.getLayout();
        layout.next(systemAdminProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButtonMouseEntered

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed
        //         ManageNetworkJPanel manageNetworkJPanel = new  ManageNetworkJPanel(userProcessContainer, system);
        //        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        //        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void manageNetworkJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageNetworkJButtonMouseExited
        // TODO add your handling code here:
        manageNetworkJButton.setBackground(backgroundBlue);
        manageNetworkJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageNetworkJButtonMouseExited

    private void manageNetworkJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageNetworkJButtonMouseEntered
        // TODO add your handling code here:
        manageNetworkJButton.setBackground(Color.orange);
        manageNetworkJButton.setForeground(Color.BLACK);

        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(systemAdminProcessContainer, system);
        systemAdminProcessContainer.add("ManageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout = (CardLayout)systemAdminProcessContainer.getLayout();
        layout.next(systemAdminProcessContainer);
    }//GEN-LAST:event_manageNetworkJButtonMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAdminJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageNetworkJButton;
    private javax.swing.JPanel systemAdminMenu;
    private javax.swing.JPanel systemAdminProcessContainer;
    private javax.swing.JSplitPane systemAdminSplitPane;
    private javax.swing.JPanel systemAdminWorkPane;
    private javax.swing.JSplitPane systemAdminWorkSplitPane;
    // End of variables declaration//GEN-END:variables
}
