/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EmployerWorkArea;

import Business.EcoSystem;
import Business.Enterprise.*;
import Business.Network.Network;
import Business.Organization.AccountsOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountsWorkRequest;
import Interface.LoginWorkArea;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shreyansh
 */
public class EmployerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private EcoSystem business;
    private  EnterpriseDirectory ed;
   
    private Enterprise enterprise;
    public EmployerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise,EnterpriseDirectory ed) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
        this.ed=ed;
        this.enterprise = enterprise;
        companyText.setText(enterprise.getName());
        employerNameText.setText(userAccount.getEmployee().getName());
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mothlyInvestmentText = new javax.swing.JTextField();
        employerNameText = new javax.swing.JTextField();
        companyText = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        selectGoalBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblNotifications = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Employer Work Area");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Employer Name");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Employer Company");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Monthly Investment");

        mothlyInvestmentText.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        employerNameText.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        employerNameText.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        employerNameText.setEnabled(false);
        employerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employerNameTextActionPerformed(evt);
            }
        });

        companyText.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        companyText.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        companyText.setEnabled(false);
        companyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyTextActionPerformed(evt);
            }
        });

        sendBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        sendBtn.setText("Send to Accounts");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Employer Work Area");

        selectGoalBtn.setBackground(new java.awt.Color(0, 51, 102));
        selectGoalBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        selectGoalBtn.setForeground(new java.awt.Color(255, 255, 255));
        selectGoalBtn.setText("Manage Federal Plans");
        selectGoalBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        selectGoalBtn.setBorderPainted(false);
        selectGoalBtn.setContentAreaFilled(false);
        selectGoalBtn.setOpaque(true);
        selectGoalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selectGoalBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selectGoalBtnMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(0, 1));

        lblNotifications.setBackground(new java.awt.Color(0, 51, 102));
        lblNotifications.setForeground(new java.awt.Color(255, 255, 255));
        lblNotifications.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotifications.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectGoalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addGap(54, 54, 54)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(selectGoalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(501, 501, 501))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(employerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(companyText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(mothlyInvestmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mothlyInvestmentText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void companyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyTextActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        int c=0;
        double investment =0;
        try{
            investment = Double.parseDouble(mothlyInvestmentText.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter valid investment amount");
            c++;
        }
        if(c==0){
            AccountsWorkRequest accRequest=new AccountsWorkRequest();
                accRequest.setAmount(investment);
                accRequest.setEnterprise(enterprise);
                accRequest.setMessage("Investment from Employer");
                accRequest.setStatus("Awaiting process");
                accRequest.setUserAccount(userAccount);
                accRequest.setSender(userAccount);
                accRequest.setRisk("NA");
                 Organization org = null;

                 for(Network network : business.getNetworkList()){
                  for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                   for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
              {
              if(organization instanceof AccountsOrganization)


            {

                    org = organization;
    //            while(!org.getWorkQueue().getWorkRequestList().isEmpty())
    //            org.getWorkQueue().getWorkRequestList().remove(0);
                break;
                }
            }

                  }

                 }
               if (org!=null){
                System.out.println("3");
                org.getWorkQueue().getWorkRequestList().add(accRequest);
                JOptionPane.showMessageDialog(null, "Request Sent Successfully");

            //userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void employerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employerNameTextActionPerformed

    private void selectGoalBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectGoalBtnMouseEntered
        // TODO add your handling code here:
        selectGoalBtn.setBackground(Color.orange);
        selectGoalBtn.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_selectGoalBtnMouseEntered

    private void selectGoalBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectGoalBtnMouseExited
        // TODO add your handling code here:
        selectGoalBtn.setBackground(LoginWorkArea.backgroundBlue);
        selectGoalBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_selectGoalBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companyText;
    private javax.swing.JTextField employerNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNotifications;
    private javax.swing.JTextField mothlyInvestmentText;
    private javax.swing.JButton selectGoalBtn;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
