/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InvestorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Interface.LoginWorkArea;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Vigensh Raghuraman
 */
public class InvestorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InvestorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization org;
    private EcoSystem system;
    private Enterprise enterprise;
    public InvestorWorkAreaJPanel(JPanel userProcessContainer,Organization organization,EcoSystem system,Enterprise enterprise)  {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org=organization;
        this.system = system;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        manageInvPlansBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InvestorProcessContainer = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(350);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        manageInvPlansBtn.setBackground(new java.awt.Color(0, 51, 102));
        manageInvPlansBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageInvPlansBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageInvPlansBtn.setText("Manage Investment Plans");
        manageInvPlansBtn.setContentAreaFilled(false);
        manageInvPlansBtn.setOpaque(true);
        manageInvPlansBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageInvPlansBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageInvPlansBtnMouseExited(evt);
            }
        });
        manageInvPlansBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInvPlansBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Investor Work Area");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageInvPlansBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(manageInvPlansBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(867, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(954, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        InvestorProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        InvestorProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(InvestorProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageInvPlansBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInvPlansBtnActionPerformed
        // TODO add your handling code here:
        
        

    }//GEN-LAST:event_manageInvPlansBtnActionPerformed

    private void manageInvPlansBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageInvPlansBtnMouseEntered
        // TODO add your handling code here:
        manageInvPlansBtn.setBackground(Color.ORANGE);
        manageInvPlansBtn.setForeground(Color.BLACK);
        ManageInvestmentPlanJPanel manageInvestmentPlanJPanel = new ManageInvestmentPlanJPanel(InvestorProcessContainer, org, system);
        InvestorProcessContainer.add("ManageInvestmentPlanJPanel", manageInvestmentPlanJPanel);
        CardLayout layout = (CardLayout) InvestorProcessContainer.getLayout();
        layout.next(InvestorProcessContainer);
    }//GEN-LAST:event_manageInvPlansBtnMouseEntered

    private void manageInvPlansBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageInvPlansBtnMouseExited
        // TODO add your handling code here:
        manageInvPlansBtn.setBackground(LoginWorkArea.backgroundBlue);
        manageInvPlansBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageInvPlansBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InvestorProcessContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageInvPlansBtn;
    // End of variables declaration//GEN-END:variables
}
