/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InvestorRole;

import Business.EcoSystem;
import Business.InvestmentPlans.InvestmentPlan;
import Business.Organization.Organization;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vigensh Raghuraman
 */
public class ManageInvestmentPlanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageInvestmentPlanJPanel
     */
    private JPanel userProcessContainer;
     private Organization org;
     private EcoSystem business;
    public ManageInvestmentPlanJPanel(JPanel userProcessContainer,Organization organization,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org=organization;
        this.business=system;
        populateInvPlanTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invPlanJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        invNameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        invRateTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        invPeriodTxtField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        planViewBtn = new javax.swing.JButton();
        planUpdateBtn = new javax.swing.JButton();
        deletePlanBtn = new javax.swing.JButton();
        invTypeCmbBox = new javax.swing.JComboBox<>();
        invPlanRiskCmbBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        invPlanAmtTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        invPlanJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plan Name", "Plan Category", "Risk Type", "Plan Amount", "Interest Rate", "Plan Period  "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invPlanJTable.setGridColor(new java.awt.Color(255, 255, 255));
        invPlanJTable.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jScrollPane1.setViewportView(invPlanJTable);
        if (invPlanJTable.getColumnModel().getColumnCount() > 0) {
            invPlanJTable.getColumnModel().getColumn(0).setResizable(false);
            invPlanJTable.getColumnModel().getColumn(1).setResizable(false);
            invPlanJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        invNameJTextField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        invNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invNameJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Type:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Risk Factor:");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Interest Rate:");

        invRateTxtField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        invRateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invRateTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Investment Period:");

        invPeriodTxtField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        invPeriodTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invPeriodTxtFieldActionPerformed(evt);
            }
        });

        submitJButton.setBackground(new java.awt.Color(0, 51, 102));
        submitJButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        planViewBtn.setBackground(new java.awt.Color(0, 51, 102));
        planViewBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        planViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        planViewBtn.setText("View");
        planViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planViewBtnActionPerformed(evt);
            }
        });

        planUpdateBtn.setBackground(new java.awt.Color(0, 51, 102));
        planUpdateBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        planUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        planUpdateBtn.setText("Update");
        planUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planUpdateBtnActionPerformed(evt);
            }
        });

        deletePlanBtn.setBackground(new java.awt.Color(0, 51, 102));
        deletePlanBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        deletePlanBtn.setForeground(new java.awt.Color(255, 255, 255));
        deletePlanBtn.setText("Delete");
        deletePlanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlanBtnActionPerformed(evt);
            }
        });

        invTypeCmbBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        invTypeCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Large Cap", "Mid Cap", "Small Cap" }));

        invPlanRiskCmbBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        invPlanRiskCmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High Risk", "Moderate Risk", "Low Risk" }));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Plan Amount:");

        invPlanAmtTxtField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        invPlanAmtTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invPlanAmtTxtFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Manage Investment Plans");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(invRateTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(invPeriodTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(invTypeCmbBox, 0, 200, Short.MAX_VALUE)
                                    .addComponent(invPlanRiskCmbBox, 0, 200, Short.MAX_VALUE)
                                    .addComponent(invPlanAmtTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(planViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(planUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(deletePlanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invTypeCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invPlanRiskCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invPlanAmtTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invPeriodTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletePlanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void invNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invNameJTextFieldActionPerformed

    private void invRateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invRateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invRateTxtFieldActionPerformed

    private void invPeriodTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invPeriodTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invPeriodTxtFieldActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        int c=0;
        String name = invNameJTextField.getText();
        String type= invTypeCmbBox.getSelectedItem().toString();
        String riskCat=invPlanRiskCmbBox.getSelectedItem().toString();
        double amount = 0; 
        double rate = 0;
        int period = 0;
        try{
            amount = Double.parseDouble(invPlanAmtTxtField.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter valid amount");
            c++;
        }
        try{
            rate = Double.parseDouble(invRateTxtField.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter valid rate");
            c++;
        }
        try{
            period = Integer.valueOf(invPeriodTxtField.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter valid period");
            c++;
        }

        if (invNameJTextField.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Please enter valid name!");
            c++;

        }
        else{
            if(c==0){
                InvestmentPlan iPlan = business.getInvPlanDirectory().addInvPlan(name,riskCat,type,rate, period, amount);
                JOptionPane.showMessageDialog(null, "New plan added");
                populateInvPlanTable();
            }
        
        }
        

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void planViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planViewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = invPlanJTable.getSelectedRow();
        if (selectedRow < 0) {
              JOptionPane.showMessageDialog(null, "Please select a row from the table first to view detail", "Warning", JOptionPane.WARNING_MESSAGE);

        }else{
            InvestmentPlan iPlan = (InvestmentPlan) invPlanJTable.getValueAt(selectedRow, 0);
            invNameJTextField.setText(iPlan.getPlanName());
            invTypeCmbBox.setSelectedItem(iPlan.getPlanCategory());
            invPlanRiskCmbBox.setSelectedItem(iPlan.getRiskType());
            invRateTxtField.setText(String.valueOf(iPlan.getPlanInterestRate()));
            invPeriodTxtField.setText(String.valueOf(iPlan.getPlanPeriod()));
            invPlanAmtTxtField.setText(String.valueOf(iPlan.getPlanAmt()));
            invNameJTextField.setEnabled(false);
            //freqJTextField.setEnabled(false);
            invPlanAmtTxtField.setEnabled(false);
        
    }   
        
        
    }//GEN-LAST:event_planViewBtnActionPerformed

    private void planUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planUpdateBtnActionPerformed
        // TODO add your handling code here:
        Double amount= Double.parseDouble(invPlanAmtTxtField.getText());
        Double rate = Double.parseDouble(invRateTxtField.getText());
        int period = Integer.valueOf(invPeriodTxtField.getText());
        
        for(InvestmentPlan plan:business.getInvPlanDirectory().getInvestmentPlanDir()){
            if (plan.getPlanName().equalsIgnoreCase(invNameJTextField.getText())){
                plan.setPlanAmt(amount);
                plan.setPlanInterestRate(rate);
                plan.setPlanPeriod(period);
                populateInvPlanTable();
            
            }
        }
        
    }//GEN-LAST:event_planUpdateBtnActionPerformed

    private void deletePlanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlanBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = invPlanJTable.getSelectedRow();
        if (selectedRow < 0) {
              JOptionPane.showMessageDialog(null, "Please select a row from the table first to view detail", "Warning", JOptionPane.WARNING_MESSAGE);

        }else{
            InvestmentPlan iPlan = (InvestmentPlan) invPlanJTable.getValueAt(selectedRow, 0);
            business.getInvPlanDirectory().removePlan(iPlan);
            populateInvPlanTable();
        }

        
    }//GEN-LAST:event_deletePlanBtnActionPerformed

    private void invPlanAmtTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invPlanAmtTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invPlanAmtTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletePlanBtn;
    private javax.swing.JTextField invNameJTextField;
    private javax.swing.JTextField invPeriodTxtField;
    private javax.swing.JTextField invPlanAmtTxtField;
    private javax.swing.JTable invPlanJTable;
    private javax.swing.JComboBox<String> invPlanRiskCmbBox;
    private javax.swing.JTextField invRateTxtField;
    private javax.swing.JComboBox<String> invTypeCmbBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton planUpdateBtn;
    private javax.swing.JButton planViewBtn;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables

    private void populateInvPlanTable() {
        DefaultTableModel model = (DefaultTableModel) invPlanJTable.getModel();

        model.setRowCount(0);
            for (InvestmentPlan iPlan : business.getInvPlanDirectory().getInvestmentPlanDir()) {
            Object[] row = new Object[6];
            row[0] = iPlan;
            row[1] = iPlan.getPlanCategory();
            row[2] = iPlan.getRiskType();
            row[3] = iPlan.getPlanAmt();
            row[4] = iPlan.getPlanInterestRate();
            row[5] = iPlan.getPlanPeriod();
            
            model.addRow(row);
        }
    }
}
