/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AccountsRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccountsWorkRequest;
import Business.WorkQueue.FinancialAdvisorWorkRequest;
import Business.WorkQueue.WorkRequest;
import Interface.LoginWorkArea;
import static Interface.LoginWorkArea.backgroundBlue;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Akshay Gavandi
 */
public class AccountsWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountsWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private EcoSystem business;
    private Enterprise enterprise;
    public AccountsWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
        this.enterprise = enterprise;
        checkNotifications();
    }

    
    private void checkNotifications(){
        for(WorkRequest request:organization.getWorkQueue().getWorkRequestList()){
            //if(((FinancialAdvisorWorkRequest)request).getCustName().equalsIgnoreCase(userAccount.getUsername())){
                if(((AccountsWorkRequest)request).isNotify()){
                    notification1.setBackground(Color.orange);
                    notification1.setForeground(Color.black);
                    notification1.setText("Customer has bought plans");
                    ((AccountsWorkRequest)request).setNotify(false);
                }
                else{
                    notification1.setText("");
                    notification1.setBackground(backgroundBlue);
                    notification1.setForeground(Color.white);
                }
            //}
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        receivablesJButton = new javax.swing.JButton();
        payablesJButton = new javax.swing.JButton();
        investmentsJButton = new javax.swing.JButton();
        notification1 = new javax.swing.JLabel();
        notification2 = new javax.swing.JLabel();
        AccountProcessContainer = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(350);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Accounts Work Area");

        receivablesJButton.setBackground(new java.awt.Color(0, 51, 102));
        receivablesJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        receivablesJButton.setForeground(new java.awt.Color(255, 255, 255));
        receivablesJButton.setText("Receivables");
        receivablesJButton.setContentAreaFilled(false);
        receivablesJButton.setOpaque(true);
        receivablesJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                receivablesJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                receivablesJButtonMouseExited(evt);
            }
        });
        receivablesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivablesJButtonActionPerformed(evt);
            }
        });

        payablesJButton.setBackground(new java.awt.Color(0, 51, 102));
        payablesJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        payablesJButton.setForeground(new java.awt.Color(255, 255, 255));
        payablesJButton.setText("Payables");
        payablesJButton.setContentAreaFilled(false);
        payablesJButton.setOpaque(true);
        payablesJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payablesJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payablesJButtonMouseExited(evt);
            }
        });
        payablesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payablesJButtonActionPerformed(evt);
            }
        });

        investmentsJButton.setBackground(new java.awt.Color(0, 51, 102));
        investmentsJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        investmentsJButton.setForeground(new java.awt.Color(255, 255, 255));
        investmentsJButton.setText("Investments");
        investmentsJButton.setContentAreaFilled(false);
        investmentsJButton.setOpaque(true);
        investmentsJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                investmentsJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                investmentsJButtonMouseExited(evt);
            }
        });
        investmentsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investmentsJButtonActionPerformed(evt);
            }
        });

        notification1.setBackground(new java.awt.Color(0, 51, 102));
        notification1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        notification1.setForeground(new java.awt.Color(255, 255, 255));
        notification1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notification1.setOpaque(true);

        notification2.setBackground(new java.awt.Color(0, 51, 102));
        notification2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        notification2.setForeground(new java.awt.Color(255, 255, 255));
        notification2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notification2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(notification1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(investmentsJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(receivablesJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(payablesJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(notification2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addComponent(receivablesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(notification1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payablesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(investmentsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notification2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(617, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        AccountProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        AccountProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(AccountProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void receivablesJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivablesJButtonMouseEntered
        // TODO add your handling code here:
        receivablesJButton.setBackground(Color.orange);
        receivablesJButton.setForeground(Color.BLACK);
        Receivables manageAccounts = new Receivables(AccountProcessContainer,userAccount,organization,enterprise);
        AccountProcessContainer.add("manageOrganizationJPanel", manageAccounts);
        CardLayout layout = (CardLayout) AccountProcessContainer.getLayout();
        layout.next(AccountProcessContainer);
        notification1.setText("");
        notification1.setBackground(backgroundBlue);
        notification1.setForeground(Color.white);
    }//GEN-LAST:event_receivablesJButtonMouseEntered

    private void receivablesJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivablesJButtonMouseExited
        // TODO add your handling code here:
        receivablesJButton.setBackground(LoginWorkArea.backgroundBlue);
        receivablesJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_receivablesJButtonMouseExited

    private void receivablesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivablesJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receivablesJButtonActionPerformed

    private void payablesJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payablesJButtonMouseEntered
        // TODO add your handling code here:
        payablesJButton.setBackground(Color.orange);
        payablesJButton.setForeground(Color.BLACK);
        Payables payables = new Payables(userProcessContainer, userAccount, organization, enterprise);
        AccountProcessContainer.add("Payables", payables);
        CardLayout layout = (CardLayout) AccountProcessContainer.getLayout();
        layout.next(AccountProcessContainer);
    }//GEN-LAST:event_payablesJButtonMouseEntered

    private void payablesJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payablesJButtonMouseExited
        // TODO add your handling code here:
        payablesJButton.setBackground(LoginWorkArea.backgroundBlue);
        payablesJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_payablesJButtonMouseExited

    private void payablesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payablesJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payablesJButtonActionPerformed

    private void investmentsJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_investmentsJButtonMouseEntered
        // TODO add your handling code here:
        investmentsJButton.setBackground(Color.orange);
        investmentsJButton.setForeground(Color.BLACK);
        ViewInvestmentPlans viewInvestmentPlans = new ViewInvestmentPlans(AccountProcessContainer,userAccount,organization,business,enterprise);
        AccountProcessContainer.add("ViewInvestmentPlans", viewInvestmentPlans);
        CardLayout layout = (CardLayout) AccountProcessContainer.getLayout();
        layout.next(AccountProcessContainer);
    }//GEN-LAST:event_investmentsJButtonMouseEntered

    private void investmentsJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_investmentsJButtonMouseExited
        // TODO add your handling code here:
        investmentsJButton.setBackground(LoginWorkArea.backgroundBlue);
        investmentsJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_investmentsJButtonMouseExited

    private void investmentsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investmentsJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_investmentsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountProcessContainer;
    private javax.swing.JButton investmentsJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel notification1;
    private javax.swing.JLabel notification2;
    private javax.swing.JButton payablesJButton;
    private javax.swing.JButton receivablesJButton;
    // End of variables declaration//GEN-END:variables
}
