/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AccountsRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akshay Gavandi
 */
public class Payables extends javax.swing.JPanel {

    /**
     * Creates new form Payables
     */
    private JPanel AccountsProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    
    public Payables(JPanel AccountsProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.AccountsProcessContainer=AccountsProcessContainer;
        this.userAccount= account;
        this.organization=organization;
        this.enterprise=enterprise;
    //    populateTable();
        readCSVPayables();
    }

     public void readCSVPayables(){
        //DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        //df.setLenient(false);
        //Date startDate = new Date("01/01/1900");
        //Date endDate = new Date("12/31/2100");
        String csvFile = "C:\\Users\\Akshay Gavandi\\Desktop\\Investment.csv";
        BufferedReader br = null;
        String line = "";
        String csvDelimiter = ",";
        DefaultTableModel model = (DefaultTableModel) tblPayables.getModel();                
        model.setRowCount(0);
        try{
            br = new BufferedReader(new FileReader(csvFile));
            line = br.readLine();//skip header
            while((line = br.readLine()) != null){
                String[] ap = line.split(csvDelimiter);
                System.out.println(ap[0]+" "+ap[1]+" "+ap[2]+" "+ap[3]+" "+ap[4]);
                Object[] row = new Object[5];
                row[0] = ap[0];;
                row[1] = ap[1];
                row[2] = ap[2];
                row[3] = ap[3];
                row[4] = ap[4];
                model.addRow(row);
            }
        }
        catch(FileNotFoundException e){
            e.printStackTrace();
        }
        catch(IOException e){
            e.printStackTrace();
        }
        finally{
            if (br!=null){
                try{
                    br.close();
                }
                catch(IOException e){
                    e.printStackTrace();
                }
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayables = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Payables");

        tblPayables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer name", "Plan Name", "Customer Type", "Amount", "Month"
            }
        ));
        tblPayables.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jScrollPane1.setViewportView(tblPayables);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayables;
    // End of variables declaration//GEN-END:variables
}
