/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.FinancialAdvisorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.WorkQueue.FinancialAdvisorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vigensh Raghuraman
 */
public class ViewCustomerRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerRequestJPanel
     */
    private JPanel userProcessContainer;
    private Organization org;
    private EcoSystem system;
    private Enterprise enterprise;
            
    public ViewCustomerRequestJPanel(JPanel userProcessContainer,Organization organization,EcoSystem system,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org=organization;
        this.system=system;
        this.enterprise=enterprise;
        populateCustReqTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custReqJTable = new javax.swing.JTable();
        serveCustomerJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("View Customer Request");

        custReqJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User name", "CustomerCategory", "Financial Goals", "Savings Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        custReqJTable.setGridColor(new java.awt.Color(255, 255, 255));
        custReqJTable.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jScrollPane1.setViewportView(custReqJTable);
        if (custReqJTable.getColumnModel().getColumnCount() > 0) {
            custReqJTable.getColumnModel().getColumn(0).setResizable(false);
            custReqJTable.getColumnModel().getColumn(1).setResizable(false);
            custReqJTable.getColumnModel().getColumn(2).setResizable(false);
            custReqJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        serveCustomerJBtn.setBackground(new java.awt.Color(0, 51, 102));
        serveCustomerJBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        serveCustomerJBtn.setForeground(new java.awt.Color(255, 255, 255));
        serveCustomerJBtn.setText("Serve");
        serveCustomerJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCustomerJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serveCustomerJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(serveCustomerJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serveCustomerJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCustomerJBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = custReqJTable.getSelectedRow();
        if (selectedRow < 0) {
              JOptionPane.showMessageDialog(null, "Please select a row from the table first to view detail", "Warning", JOptionPane.WARNING_MESSAGE);

        }else{
        String name = String.valueOf(custReqJTable.getValueAt(selectedRow,0));
        String type= String.valueOf(custReqJTable.getValueAt(selectedRow, 1));
        SuggestFinancialPlanJpanel suggestFinancialPlanJpanel = new SuggestFinancialPlanJpanel(userProcessContainer,org,system,name,enterprise,type);
        userProcessContainer.add("suggestFinancialPlanJpanel", suggestFinancialPlanJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_serveCustomerJBtnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable custReqJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton serveCustomerJBtn;
    // End of variables declaration//GEN-END:variables

    private void populateCustReqTable() {
        DefaultTableModel model = (DefaultTableModel)custReqJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request:org.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = ((FinancialAdvisorWorkRequest)request).getCustName();
            row[1] = ((FinancialAdvisorWorkRequest)request).getCategory();
            row[2] = ((FinancialAdvisorWorkRequest)request).getGoals();
            row[3] = ((FinancialAdvisorWorkRequest)request).getSavings();
            model.addRow(row);
            
        }
        
    }
}
