/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerWorkArea;
import Business.Enterprise.Enterprise;
import Business.WorkQueue.FinancialAdvisorWorkRequest;

import java.awt.CardLayout;
import java.awt.Color;
import Business.FinancialAdvisorAndPlans.FinancialAdvisor;
import Business.Organization.FinancialAdvisorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Shreyansh
 */
public class CustomerRequestPage extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    //private FinancialAdvisor financialAdvisor;
    private Organization organization;
    private UserAccount userAccount;
   
    public CustomerRequestPage(JPanel userProcessContainer, Enterprise enterprise,Organization organization,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        //this.financialAdvisor=financialAdvisor;
        this.organization=organization;
        this.userAccount=userAccount;
    }

    public void updateFields(String type){
        if(type.equals("Salaried")){
            salaryCBox.setEnabled(true);
            jLabel7.setText("EMI Amount");
            savingsTxt.setEnabled(true);
        }
        else if(type.equals("Retirees")){
            salaryCBox.setEnabled(false);
            jLabel7.setText("Saving Amount");
            savingsTxt.setEnabled(true);
            
        }
        else if(type.equals("Dependents")){
            salaryCBox.setEnabled(false);
            jLabel7.setText("Savings");
            savingsTxt.setEnabled(false);
            savingsTxt.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        selectGoalCBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        doneBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        salaryCBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        customerCategoryCBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        savingsTxt = new javax.swing.JTextField();
        lblBack = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ageTxt1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        customerCategoryCBox1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Customer Request Work Area");

        selectGoalCBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        selectGoalCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Long Term Goals", "Short Term Goals" }));
        selectGoalCBox.setSelectedIndex(-1);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Comments");

        doneBtn.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        doneBtn.setText("Submit Request");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Select Category");

        salaryCBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        salaryCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "<$ 50,000 ", "$50,000-$80,000", "$80.000-$100,000", ">$100,000" }));
        salaryCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryCBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Annual Salary Range");

        customerCategoryCBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        customerCategoryCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        customerCategoryCBox.setSelectedIndex(-1);

        commentsTextArea.setColumns(20);
        commentsTextArea.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        commentsTextArea.setRows(5);
        jScrollPane1.setViewportView(commentsTextArea);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Investment");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Select Goals");

        savingsTxt.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Age");

        ageTxt1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ageTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxt1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Sex");

        customerCategoryCBox1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        customerCategoryCBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Salaried", "Retirees", "Dependents" }));
        customerCategoryCBox1.setSelectedIndex(-1);
        customerCategoryCBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCategoryCBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(customerCategoryCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(ageTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(savingsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(salaryCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(customerCategoryCBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(selectGoalCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblBack)
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCategoryCBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectGoalCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCategoryCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salaryCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryCBoxActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
//           userProcessContainer.remove(this);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_lblBackMouseClicked

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        // TODO add your handling code here:
        
        try{
            int age = Integer.parseInt(ageTxt1.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter valid age");
        }
        double savings=0;
        try{
            savings = Double.parseDouble(savingsTxt.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter valid investment");
        }
        FinancialAdvisorWorkRequest request= new FinancialAdvisorWorkRequest();
        request.setNotify(true);
        request.setCategory(customerCategoryCBox1.getSelectedItem().toString());
        request.setSalary(salaryCBox.getSelectedItem().toString());
        request.setSavings(String.valueOf(savings));
        request.setGoals(selectGoalCBox.getSelectedItem().toString());
        request.setCustName(userAccount.getUsername());
        // request.setSender(account);
         //request.setFinancialAdvisor(financialAdvisor);

        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof FinancialAdvisorOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            //userAccount.getWorkQueue().getWorkRequestList().add(request);
        }

        
        
       JOptionPane.showMessageDialog(null, "Request Sent Successfully");

    }//GEN-LAST:event_doneBtnActionPerformed

    private void customerCategoryCBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCategoryCBox1ActionPerformed
        // TODO add your handling code here:
        String type = customerCategoryCBox1.getSelectedItem().toString();
        updateFields(type);
    }//GEN-LAST:event_customerCategoryCBox1ActionPerformed

    private void ageTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt1;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JComboBox customerCategoryCBox;
    private javax.swing.JComboBox customerCategoryCBox1;
    private javax.swing.JButton doneBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JComboBox<Object> salaryCBox;
    private javax.swing.JTextField savingsTxt;
    private javax.swing.JComboBox selectGoalCBox;
    // End of variables declaration//GEN-END:variables
}
