/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package Interface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import static Interface.LoginWorkArea.backgroundBlue;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author  Akshay Gavandi
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        enterpriseAdminWorkMenu = new javax.swing.JPanel();
        manageOrganizationJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        manageUserJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enterpriseAdminWorkPanel = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        jSplitPane1.setDividerLocation(350);

        enterpriseAdminWorkMenu.setBackground(new java.awt.Color(0, 51, 102));
        enterpriseAdminWorkMenu.setForeground(new java.awt.Color(255, 255, 255));

        manageOrganizationJButton.setBackground(new java.awt.Color(0, 51, 102));
        manageOrganizationJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageOrganizationJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.setContentAreaFilled(false);
        manageOrganizationJButton.setOpaque(true);
        manageOrganizationJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageOrganizationJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageOrganizationJButtonMouseExited(evt);
            }
        });
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });

        manageEmployeeJButton.setBackground(new java.awt.Color(0, 51, 102));
        manageEmployeeJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.setContentAreaFilled(false);
        manageEmployeeJButton.setOpaque(true);
        manageEmployeeJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageEmployeeJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageEmployeeJButtonMouseExited(evt);
            }
        });
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setBackground(new java.awt.Color(0, 51, 102));
        enterpriseLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setBackground(new java.awt.Color(0, 51, 102));
        valueLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("<value>");

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enterprise Admin ");

        manageUserJButton.setBackground(new java.awt.Color(0, 51, 102));
        manageUserJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        manageUserJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageUserJButton.setText("Manage User");
        manageUserJButton.setContentAreaFilled(false);
        manageUserJButton.setOpaque(true);
        manageUserJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageUserJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageUserJButtonMouseExited(evt);
            }
        });
        manageUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserJButtonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Work Area");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout enterpriseAdminWorkMenuLayout = new javax.swing.GroupLayout(enterpriseAdminWorkMenu);
        enterpriseAdminWorkMenu.setLayout(enterpriseAdminWorkMenuLayout);
        enterpriseAdminWorkMenuLayout.setHorizontalGroup(
            enterpriseAdminWorkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterpriseAdminWorkMenuLayout.createSequentialGroup()
                .addGroup(enterpriseAdminWorkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(enterpriseAdminWorkMenuLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(enterpriseLabel)
                        .addGap(41, 41, 41)
                        .addComponent(valueLabel))
                    .addGroup(enterpriseAdminWorkMenuLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(enterpriseAdminWorkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(enterpriseAdminWorkMenuLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3))))
                    .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(manageUserJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(enterpriseAdminWorkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enterpriseAdminWorkMenuLayout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 30, Short.MAX_VALUE)))
        );
        enterpriseAdminWorkMenuLayout.setVerticalGroup(
            enterpriseAdminWorkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterpriseAdminWorkMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(enterpriseAdminWorkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(manageEmployeeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
            .addGroup(enterpriseAdminWorkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enterpriseAdminWorkMenuLayout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(662, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(enterpriseAdminWorkMenu);

        enterpriseAdminWorkPanel.setBackground(new java.awt.Color(255, 255, 255));
        enterpriseAdminWorkPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(enterpriseAdminWorkPanel);

        add(jSplitPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUserJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonMouseEntered
        // TODO add your handling code here:
        manageOrganizationJButton.setBackground(Color.orange);
        manageOrganizationJButton.setForeground(Color.BLACK);
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(enterpriseAdminWorkPanel, enterprise.getOrganizationDirectory(),enterprise);
        enterpriseAdminWorkPanel.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) enterpriseAdminWorkPanel.getLayout();
        layout.next(enterpriseAdminWorkPanel);
    }//GEN-LAST:event_manageOrganizationJButtonMouseEntered

    private void manageEmployeeJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonMouseEntered
        // TODO add your handling code here:
        manageEmployeeJButton.setBackground(Color.orange);
        manageEmployeeJButton.setForeground(Color.BLACK);
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(enterpriseAdminWorkPanel, enterprise.getOrganizationDirectory());
        enterpriseAdminWorkPanel.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) enterpriseAdminWorkPanel.getLayout();
        layout.next(enterpriseAdminWorkPanel);
    }//GEN-LAST:event_manageEmployeeJButtonMouseEntered

    private void manageUserJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserJButtonMouseEntered
        // TODO add your handling code here:
        manageUserJButton.setBackground(Color.orange);
        manageUserJButton.setForeground(Color.BLACK);
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(enterpriseAdminWorkPanel, enterprise);
        enterpriseAdminWorkPanel.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) enterpriseAdminWorkPanel.getLayout();
        layout.next(enterpriseAdminWorkPanel);
    }//GEN-LAST:event_manageUserJButtonMouseEntered

    private void manageOrganizationJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonMouseExited
        // TODO add your handling code here:
        manageOrganizationJButton.setBackground(backgroundBlue);
        manageOrganizationJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageOrganizationJButtonMouseExited

    private void manageEmployeeJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonMouseExited
        // TODO add your handling code here:
        manageEmployeeJButton.setBackground(backgroundBlue);
        manageEmployeeJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageEmployeeJButtonMouseExited

    private void manageUserJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserJButtonMouseExited
        // TODO add your handling code here:
        manageUserJButton.setBackground(backgroundBlue);
        manageUserJButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_manageUserJButtonMouseExited
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel enterpriseAdminWorkMenu;
    private javax.swing.JPanel enterpriseAdminWorkPanel;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton manageUserJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
